# NOTE: docker compose v3 removed group_add

version: '3'

services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  jenkins:
